- name: variables from file
  hosts: localhost
  become: yes
  vars_files:
    - variables.yaml
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "I am learning {{course}} and my tainer is {{trainer}} and the duration is {{duration}}"
