- name: variables from inventory
  hosts: localhost
  become: yes
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "I am learning {{course}} and my tainer is {{trainer}} and the duratimhon is {{duration}}"
