- name: checking the roboshop user existed or not
  hosts: local host
  become: yes
  tasks:
    - name: checking the user
      ansible.builtin.command: id roboshop
        register: user # it will store  the output in the user variable
        ignore_errors: yes
        msg: "{{user}}"
      
