- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: printing user names in loop
    ansible.builtin.debug:
      msg: "hi Good morning {{user}}"
    loops:
      - ravi
      - sam
      - raju